

version: '3.9'

services:
  # Aplicacion Node.js
  app:
    build: .
    container_name: bildyapp-api
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_URI: mongodb://mongo:27017/bildyapp_final
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRES: ${JWT_ACCESS_EXPIRES}
      JWT_REFRESH_EXPIRES: ${JWT_REFRESH_EXPIRES}
      PUBLIC_URL: ${PUBLIC_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    volumes:
      - uploads:/app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  # MongoDB
  mongo:
    image: mongo:7
    container_name: bildyapp-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
  uploads: